#
# Private
#

if [[ -f ~/.localrc ]]; then
    source ~/.localrc
fi

#
# Oh-my-zsh
#

# Path to your oh-my-zsh installation.
export ZSH=/home/dobmayer/.oh-my-zsh
ZSH_THEME=""

# Command execution timestamp format shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Start tmux at startup
export ZSH_TMUX_AUTOSTART=false

# Enable zsh plugins
plugins=(colored-man-pages docker git history sudo systemd tmux vagrant zsh_reload)
source $ZSH/oh-my-zsh.sh

# completions automatically find new executables in the path
zstyle ':completion:*' rehash true

#
# Settings
#

PROMPT_SYMBOL='❯'
PROMPT='%(?.%F{207}.%F{160})$PROMPT_SYMBOL%f '

# 10ms for key sequences
KEYTIMEOUT=1

# Do not ask for confirmation for `rm *' or `rm path/*'
setopt rm_star_silent

# Set for colored man pages
export GROFF_NO_SGR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vimx'
else
  # Will be nvim
  export EDITOR='vimx'
fi

#
# Aliases
#

if [ -e /usr/bin/vimx ]; then
  alias vim='/usr/bin/vimx'
fi

alias la='exa -abghl --git --color=automatic'
alias o='xdg-open'
alias rp="export RPROMPT='%F{40}%~'"
alias -g M="| more"

alias zshrc="$EDITOR ~/.zshrc" 
alias tmux.conf="$EDITOR ~/.tmux.conf"
alias vimrc="$EDITOR ~/.vimrc"

# DNF
alias dnfp='dnf provides'
alias dnfli='dnf list --installed'
alias dnfla='dnf list --available'
alias dnfu='sudo dnf upgrade'
alias dnfi='sudo dnf install'

export GOPATH=$HOME
export PACKER_CACHE_DIR=$HOME/.packer.d/cache
export VAGRANT_DEFAULT_PROVIDER='libvirt'

#
# Functions
#

# set alacritty's opacity
so() {
  local opacity=$1
  sed -Ei "/^background_opacity/s/[0-9].[0-9]+/${opacity}/" $HOME/.alacritty.yml
}
