#
# Private
#

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi

# overload system default 256-color palette with precise gruvbox colors
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"

#
# Oh-my-zsh
#

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""

# Command execution timestamp format shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Start tmux at startup
#export ZSH_TMUX_AUTOSTART=true

# Not allow zsh to rename window titles
DISABLE_AUTO_TITLE="true"

# Enable zsh plugins
plugins=(colored-man-pages docker extract git history sudo tmux zsh_reload)
source $ZSH/oh-my-zsh.sh

# completions automatically find new executables in the path
zstyle ':completion:*' rehash true

#
# Settings
#

PROMPT_SYMBOL='❯'
PROMPT='%(?.%F{207}.%F{160})$PROMPT_SYMBOL%f '
RPROMPT='%F{40}%~$(git_branch)'

# 10ms for key sequences
KEYTIMEOUT=1

# Do not ask for confirmation for `rm *' or `rm path/*'
setopt rm_star_silent

# Set for colored man pages
export GROFF_NO_SGR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  # Will be nvim
  export EDITOR='vim'
fi
#
# Aliases
#

if [ -e /usr/bin/vimx ]; then
  alias vim='/usr/bin/vimx'
fi

# system
alias vi='vim'
alias la='exa -abghl --git --color=automatic'
alias o='xdg-open'
alias -g M="| more"
alias hu='setxkbmap hu'
alias us='setxkbmap us'

# edit configs
alias zshrc="$EDITOR ~/.zshrc" 
alias tmux.conf="$EDITOR ~/.tmux.conf"
alias vimrc="$EDITOR ~/.vimrc"
alias i3config="$EDITOR ~/.config/i3/config"

# dnf
#alias dnfp='dnf provides'
#alias dnfli='dnf list --installed'
#alias dnfla='dnf list --available'
#alias dnfu='sudo dnf upgrade'
#alias dnfi='sudo dnf install'

# go
alias gorun='tput clear; go run main.go'
alias gd='go doc'
alias github='cd $GOPATH/src/github.com'
alias depup='dep ensure -v && dep ensure -v -update'

# Bitrise
alias br='bitrise run'
export MY_STEPLIB_REPO_FORK_GIT_URL=git@github.com:kdobmayer/bitrise-steplib.git

# environment variables
#export GOPATH=/go
export PACKER_CACHE_DIR=$HOME/.packer.d/cache
#export VAGRANT_DEFAULT_PROVIDER='libvirt'

#
# Functions
#

# i3 lock
lock() {
  scrot /tmp/screen.png
  convert /tmp/screen.png -blur 0x5 /tmp/screen.png
  convert /tmp/screen.png ~/Pictures/lock.png -gravity center -composite -matte /tmp/screen.png
  i3lock -u -e -i /tmp/screen.png
  rm /tmp/screen.png
}

# toggle right prompt
rpr() {
  if [[ -z "$RPROMPT" ]]; then
    RPROMPT='%F{41}%~$(git_branch)'
  else
    RPROMPT=""
  fi
}

# set alacritty's opacity
so() {
  local opacity=$1
  sed -Ei "/^background_opacity/s/[0-9].[0-9]+/${opacity}/" $HOME/.config/alacritty/alacritty.yml
}

git_branch() {
  if [[ -d .git ]]; then
    echo "%F{123} $(git branch | awk '/\*/ {print $2}')%f"
  fi
}
