#
# Private
#

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi

#
# Oh-my-zsh
#

# Path to your oh-my-zsh installation.
export ZSH=/home/dobmayer/.oh-my-zsh
ZSH_THEME=""

# Command execution timestamp format shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Start tmux at startup
export ZSH_TMUX_AUTOSTART=false

# Enable zsh plugins
plugins=(colored-man-pages docker extract git history sudo systemd vagrant zsh_reload)
source $ZSH/oh-my-zsh.sh

# completions automatically find new executables in the path
zstyle ':completion:*' rehash true

#
# Settings
#

PROMPT_SYMBOL='❯'
PROMPT='%(?.%F{207}.%F{160})$PROMPT_SYMBOL%f '

# 10ms for key sequences
KEYTIMEOUT=1

# Do not ask for confirmation for `rm *' or `rm path/*'
setopt rm_star_silent

# Set for colored man pages
export GROFF_NO_SGR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vimx'
else
  # Will be nvim
  export EDITOR='vimx'
fi

#
# Aliases
#

if [ -e /usr/bin/vimx ]; then
  alias vim='/usr/bin/vimx'
fi

# system
alias la='exa -abghl --git --color=automatic'
alias o='xdg-open'
alias -g M="| more"
alias hu='setxkbmap hu'
alias us='setxkbmap us'

# edit configs
alias zshrc="$EDITOR ~/.zshrc" 
alias tmux.conf="$EDITOR ~/.tmux.conf"
alias vimrc="$EDITOR ~/.vimrc"
alias i3config="$EDITOR ~/.config/i3/config"

# dnf
alias dnfp='dnf provides'
alias dnfli='dnf list --installed'
alias dnfla='dnf list --available'
alias dnfu='sudo dnf upgrade'
alias dnfi='sudo dnf install'

# go
alias gorun='tput clear; go run main.go'
alias gd='go doc'

# Bitrise
alias br='bitrise run'

# environment variables
export GOPATH=$HOME
export PACKER_CACHE_DIR=$HOME/.packer.d/cache
export VAGRANT_DEFAULT_PROVIDER='libvirt'

#
# Functions
#

# toggle right prompt
rpr() {
  if [[ -z "$RPROMPT" ]]; then
    RPROMPT='%F{40}%~'
  else
    RPROMPT=""
  fi
}

# set alacritty's opacity
so() {
  local opacity=$1
  sed -Ei "/^background_opacity/s/[0-9].[0-9]+/${opacity}/" $HOME/.config/alacritty/alacritty.yml
}

# override builtin exit when in tmux
# exit() {
#   if [[ -z "$TMUX" ]]; then
#     builtin exit
#   else
#     tmux kill-window \; detach
#   fi
# }
# if [[ -z "$TMUX" ]] && tmux has-session -t $USER &> /dev/null; then
#     exec tmux new-session -t $USER \; \
#       set-option destroy-unattached \; \
#       new-window
# fi

proxyoff() {
	unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
	sudo sed -i s/^proxy/#proxy/g /etc/dnf/dnf.conf
	sudo sed -i s/^Environment/#Environment/g /etc/systemd/system/docker.service.d/http-proxy.conf
	sudo systemctl daemon-reload
	sudo systemctl restart docker
}

proxyon() {
	export http_proxy=http://10.144.1.10:8080 \
		https_proxy=http://10.144.1.10:8080 \
		no_proxy="localhost,127.0.0.0/8,::1,.ntms.nsn-rdnet.net,.nokia.com" \
    HTTP_PROXY=http://10.144.1.10:8080 \
    HTTPS_PROXY=http://10.144.1.10:8080 \
    NO_PROXY="localhost,127.0.0.0/8,::1,.ntms.nsn-rdnet.net,.nokia.com" 
  sudo sed -i s/^#proxy/proxy/g /etc/dnf/dnf.conf
	sudo sed -i s/^#Environment/Environment/g /etc/systemd/system/docker.service.d/http-proxy.conf
	sudo systemctl daemon-reload
	sudo systemctl restart docker
}
