#
# Private
#

if [[ -a ~/.localrc ]]; then
    source ~/.localrc
fi

#
# Oh-my-zsh
#

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""

# Command execution timestamp format shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Start tmux at startup
export ZSH_TMUX_AUTOSTART=true

# Enable zsh plugins
plugins=(colored-man-pages docker extract git history sudo tmux zsh_reload)
source $ZSH/oh-my-zsh.sh

# completions automatically find new executables in the path
zstyle ':completion:*' rehash true

#
# Settings
#

PROMPT_SYMBOL='❯'
PROMPT='%(?.%F{207}.%F{160})$PROMPT_SYMBOL%f '
RPROMPT='%F{40}%~'

# 10ms for key sequences
KEYTIMEOUT=1

# Do not ask for confirmation for `rm *' or `rm path/*'
setopt rm_star_silent

# Set for colored man pages
export GROFF_NO_SGR=1

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  # Will be nvim
  export EDITOR='vim'
fi

#
# Aliases
#

#if [ -e /usr/bin/vimx ]; then
#  alias vim='/usr/bin/vimx'
#fi

# system
alias vi='vim'
alias la='exa -abghl --git --color=automatic'
alias o='xdg-open'
alias -g M="| more"
alias hu='setxkbmap hu'
alias us='setxkbmap us'

# edit configs
alias zshrc="$EDITOR ~/.zshrc" 
alias tmux.conf="$EDITOR ~/.tmux.conf"
alias vimrc="$EDITOR ~/.vimrc"
alias i3config="$EDITOR ~/.config/i3/config"

# dnf
#alias dnfp='dnf provides'
#alias dnfli='dnf list --installed'
#alias dnfla='dnf list --available'
#alias dnfu='sudo dnf upgrade'
#alias dnfi='sudo dnf install'

# go
alias gorun='tput clear; go run main.go'
alias gd='go doc'
alias github='cd $GOPATH/src/github.com'
alias depup='dep ensure -v && dep ensure -v -update'

# Bitrise
alias br='bitrise run'
alias bla='bitrise-log-analyzer'

# environment variables
export GOPATH=/go
export PACKER_CACHE_DIR=$HOME/.packer.d/cache
export VAGRANT_DEFAULT_PROVIDER='libvirt'

#
# Functions
#

# toggle right prompt
rpr() {
  if [[ -z "$RPROMPT" ]]; then
    RPROMPT='%F{40}%~'
  else
    RPROMPT=""
  fi
}

# set alacritty's opacity
so() {
  local opacity=$1
  sed -Ei "/^background_opacity/s/[0-9].[0-9]+/${opacity}/" $HOME/.config/alacritty/alacritty.yml
}

# override builtin exit when in tmux
# exit() {
#   if [[ -z "$TMUX" ]]; then
#     builtin exit
#   else
#     tmux kill-window \; detach
#   fi
# }
# if [[ -z "$TMUX" ]] && tmux has-session -t $USER &> /dev/null; then
#     exec tmux new-session -t $USER \; \
#       set-option destroy-unattached \; \
#       new-window
# fi
